### ISSUE TITLE
fatal error while evaluating conditional: item.version == "9.4"

### ISSUE THREAD

**Issue by sergiosdlima** [lesovsky/ansible-postgresql-on-el6#1]
I added the lesovsky.postgresql-on-el6 role in my playbook, but this is causing an error, see:

TASK: [lesovsky.postgresql-on-el6 | Stage 1: install repository package] *****\* 
fatal: [institucional] => error while evaluating conditional: item.version == "9.4"

**Comment by sergiosdlima** [comment]
The #2 fix this problem for me.

**Comment by lesovsky** [comment]
Hi, I got your pull request. Thanks!
